---
name: Lint PR Title
on:
  pull_request_target:
    types: [opened, edited, synchronize]
permissions: read-all
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Check PR title
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on the PR if the title doesn't follow the Conventional Commits specification
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          header: pr-title-lint-error
          message: |
            Thank you for opening this pull request! üëãüèº

            In order to streamline our release process and maintain a consistent commit history, we require pull request (PR) titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

            Based on our linter, it looks like your proposed title needs to be adjusted. Here's the error message we received:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - name: Delete the previous comment once the PR title has been updated
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          header: pr-title-lint-error
          delete: true
